"""empty message

Revision ID: 2836ac492ced
Revises: 633c705e372f
Create Date: 2023-07-28 23:03:32.368381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2836ac492ced'
down_revision = '633c705e372f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('item_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=3, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('item_price',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###
