"""empty message

Revision ID: 3633f44b087d
Revises: 
Create Date: 2023-08-01 15:37:47.390125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3633f44b087d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=64), nullable=True),
    sa.Column('item_type', sa.String(length=64), nullable=True),
    sa.Column('item_price', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_history_id', sa.Integer(), nullable=True),
    sa.Column('menu_items_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_items_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['order_history_id'], ['orders_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders_history')
    op.drop_table('menu')
    op.drop_table('customers')
    # ### end Alembic commands ###
