"""empty message

Revision ID: 633c705e372f
Revises: 9df4f4d80a96
Create Date: 2023-07-28 22:59:31.734339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633c705e372f'
down_revision = '9df4f4d80a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('item_price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('item_price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
