"""empty message

Revision ID: a3e14982ed33
Revises: ba1b15b1c0fe
Create Date: 2023-08-01 04:10:55.851142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3e14982ed33'
down_revision = 'ba1b15b1c0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_history', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_history', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
